import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const openExpress = () =>{

    window.ccEverywhere.createDesign({
      callbacks: {
        onPublishStart: () => {},
        onPublish: async (publishParams) => {
          const b64 = publishParams.asset?.data;
          const b64Data = b64.replace("data:image/png;base64,", "");

          console.log(b64Data)
        },
      },
      outputParams: {
        fileType: "png",
        outputType: "base64",
      },
      inputParams: {
        canvasAspectId: "1:2",
        templateType: "Flyers",
      },
    });

  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a onClick={openExpress} className={styles.card}>
            <h2>Adobe Express &rarr;</h2>
            <p>Open the Express editor.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
